services:
    mgweb:
        image: nginx:1.21.5-alpine
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        restart: unless-stopped
        volumes:
            - /opt/www:/opt/www
            - ./data/nginx-dev:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - /tmp:/tmp/host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
            - "443:443"
    # certbot:
    #     image: certbot/certbot
    #     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    #     restart: unless-stopped
    #     volumes:
    #         - ./data/certbot/conf:/etc/letsencrypt
    #         - ./data/certbot/www:/var/www/certbot
