version: '3.7'
services:
    mgweb:
        image: nginx:1.21.5-alpine            
        restart: always        
        volumes:
            - /opt/www:/opt/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - /tmp:/tmp/host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo              
        extra_hosts:
            - "host.docker.internal:host-gateway"              
        ports:
            - "80:80"
