version: '3.7'
services:
    mgweb:
        image: nginx:1.21.5-alpine            
        restart: always        
        volumes:
            - /opt/www:/opt/www
            - ./data/nginx:/etc/nginx/conf.d
            - /tmp:/tmp/host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /usr/share/zoneinfo:/usr/share/zoneinfo              
        extra_hosts:
            - "host.docker.internal:host-gateway"              
        ports:
            - "80:80"
            - "443:443"
    certbot:
        image: certbot/certbot
