version: '3.7'
services:
    mgweb:
        image: nginx:1.21.5-alpine            
        volumes:
            - /opt/www:/opt/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - /tmp:/tmp/host
        extra_hosts:
            - "host.docker.internal:host-gateway"              
        ports:
            - "80:80"
